-- MySQL Script generated by MySQL Workbench
-- Wed May 28 13:49:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema provisys
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema provisys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `provisys` DEFAULT CHARACTER SET utf8 ;
USE `provisys` ;

-- -----------------------------------------------------
-- Table `provisys`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`rol` (
  `id_rol` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(32) NOT NULL,
  `descripción` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `id_rol_UNIQUE` (`id_rol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`credencial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`credencial` (
  `nombre_usuario` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`nombre_usuario`),
  UNIQUE INDEX `nombre_usuario_UNIQUE` (`nombre_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`usuario` (
  `nombre_usuario` VARCHAR(255) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `nombres` VARCHAR(46) NOT NULL,
  `apellidos` VARCHAR(46) NOT NULL,
  `correo_electrónico` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(16) NOT NULL,
  `telefono_secundario` VARCHAR(16) NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `id_rol` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`nombre_usuario`),
  UNIQUE INDEX `correo_electrónico_UNIQUE` (`correo_electrónico` ASC) VISIBLE,
  INDEX `fk_usuarios_roles1_idx` (`id_rol` ASC) VISIBLE,
  INDEX `fk_usuarios_credencial1_idx` (`nombre_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `provisys`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_credencial1`
    FOREIGN KEY (`nombre_usuario`)
    REFERENCES `provisys`.`credencial` (`nombre_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`pedido` (
  `id_pedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_pedido` DATETIME NOT NULL,
  `estado` INT NOT NULL,
  `nombre_usuario` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_pedido`),
  UNIQUE INDEX `id_pedido_UNIQUE` (`id_pedido` ASC) VISIBLE,
  INDEX `fk_pedidos_usuario1_idx` (`nombre_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_usuario1`
    FOREIGN KEY (`nombre_usuario`)
    REFERENCES `provisys`.`usuario` (`nombre_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`permiso` (
  `id_permiso` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(32) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_permiso`),
  UNIQUE INDEX `id_permiso_UNIQUE` (`id_permiso` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`metodo_de_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`metodo_de_pago` (
  `id_metodo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_metodo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_metodo`),
  UNIQUE INDEX `id_metodo_UNIQUE` (`id_metodo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`pago` (
  `id_pago` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `monto` DECIMAL(12,2) NOT NULL,
  `verificado` TINYINT ZEROFILL NOT NULL,
  `nro_referencia` VARCHAR(255) NOT NULL,
  `id_pedido` INT UNSIGNED NOT NULL,
  `id_metodo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_pago`),
  INDEX `fk_venta_pedidos1_idx` (`id_pedido` ASC) VISIBLE,
  UNIQUE INDEX `id_venta_UNIQUE` (`id_pago` ASC) VISIBLE,
  INDEX `fk_venta_metodo_de_pago1_idx` (`id_metodo` ASC) VISIBLE,
  CONSTRAINT `fk_venta_pedidos1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `provisys`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_metodo_de_pago1`
    FOREIGN KEY (`id_metodo`)
    REFERENCES `provisys`.`metodo_de_pago` (`id_metodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`categoria_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`categoria_producto` (
  `id_categoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`iva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`iva` (
  `id_iva` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_iva` VARCHAR(45) NOT NULL,
  `iva` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`id_iva`),
  UNIQUE INDEX `id_iva_UNIQUE` (`id_iva` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`afiliado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`afiliado` (
  `id_afiliado` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(128) NOT NULL,
  `telefono` VARCHAR(16) NOT NULL,
  `correo` VARCHAR(256) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_afiliado`),
  UNIQUE INDEX `id_afiliado_UNIQUE` (`id_afiliado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`proveedor` (
  `id_proveedor` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_proveedor`),
  CONSTRAINT `fk_proveedor_afiliado1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `provisys`.`afiliado` (`id_afiliado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`producto` (
  `id_producto` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `precio` DECIMAL(12,2) NOT NULL,
  `id_categoria` INT UNSIGNED NOT NULL,
  `id_iva` INT UNSIGNED NOT NULL,
  `id_proveedor` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_productos_categorias_producto1_idx` (`id_categoria` ASC) VISIBLE,
  UNIQUE INDEX `id_producto_UNIQUE` (`id_producto` ASC) VISIBLE,
  INDEX `fk_productos_iva1_idx` (`id_iva` ASC) VISIBLE,
  INDEX `fk_producto_proveedor1_idx` (`id_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_productos_categorias_producto1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `provisys`.`categoria_producto` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_iva1`
    FOREIGN KEY (`id_iva`)
    REFERENCES `provisys`.`iva` (`id_iva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_proveedor1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `provisys`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`almacen` (
  `id_almacen` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_almacen`),
  UNIQUE INDEX `id_almacen_UNIQUE` (`id_almacen` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`movimiento_de_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`movimiento_de_inventario` (
  `id_perdida` INT UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `cantidad_producto` INT UNSIGNED NOT NULL,
  `tipo_movimiento` ENUM("abastecimiento", "perdida", "autoventa", "preventa") NOT NULL,
  `id_almacen` INT NOT NULL,
  `id_producto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_perdida`),
  UNIQUE INDEX `id_perdida_UNIQUE` (`id_perdida` ASC) VISIBLE,
  INDEX `fk_perdidas_almacenes1_idx` (`id_almacen` ASC) VISIBLE,
  INDEX `fk_perdidas_productos1_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_perdidas_almacenes1`
    FOREIGN KEY (`id_almacen`)
    REFERENCES `provisys`.`almacen` (`id_almacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perdidas_productos1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `provisys`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`cliente_preventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`cliente_preventa` (
  `id_cliente` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  CONSTRAINT `fk_cliente_preventa_afiliado1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `provisys`.`afiliado` (`id_afiliado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`nota_de_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`nota_de_venta` (
  `id_nota` INT UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `id_cliente` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_nota`),
  UNIQUE INDEX `id_nota_UNIQUE` (`id_nota` ASC) VISIBLE,
  INDEX `fk_nota_de_venta_cliente_preventa1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_nota_de_venta_cliente_preventa1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `provisys`.`cliente_preventa` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`permisos_de_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`permisos_de_rol` (
  `id_rol` INT UNSIGNED NOT NULL,
  `id_permiso` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_rol`, `id_permiso`),
  INDEX `fk_roles_has_permisos_permisos1_idx` (`id_permiso` ASC) VISIBLE,
  INDEX `fk_roles_has_permisos_roles1_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_roles_has_permisos_roles1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `provisys`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_has_permisos_permisos1`
    FOREIGN KEY (`id_permiso`)
    REFERENCES `provisys`.`permiso` (`id_permiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`detalles_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`detalles_pedido` (
  `id_pedido` INT UNSIGNED NOT NULL,
  `id_producto` VARCHAR(255) NOT NULL,
  `cantidad_producto` INT UNSIGNED NOT NULL,
  `precio_de_venta` DECIMAL(12,2) NOT NULL,
  `iva_de_venta` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_producto`),
  INDEX `fk_pedidos_has_productos_productos1_idx` (`id_producto` ASC) VISIBLE,
  INDEX `fk_pedidos_has_productos_pedidos1_idx` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_has_productos_pedidos1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `provisys`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_productos_productos1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `provisys`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`productos_por_nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`productos_por_nota` (
  `id_producto` VARCHAR(255) NOT NULL,
  `id_nota` INT UNSIGNED NOT NULL,
  `cantidad_producto` INT UNSIGNED NOT NULL,
  `precio_de_venta` DECIMAL(12,2) NOT NULL,
  `iva_de_venta` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`id_producto`, `id_nota`),
  INDEX `fk_productos_has_notas_de_venta_notas_de_venta1_idx` (`id_nota` ASC) VISIBLE,
  INDEX `fk_productos_has_notas_de_venta_productos1_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_productos_has_notas_de_venta_productos1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `provisys`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_has_notas_de_venta_notas_de_venta1`
    FOREIGN KEY (`id_nota`)
    REFERENCES `provisys`.`nota_de_venta` (`id_nota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provisys`.`productos_en_almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `provisys`.`productos_en_almacen` (
  `id_producto` VARCHAR(255) NOT NULL,
  `id_almacen` INT NOT NULL,
  `stock_disponible` INT ZEROFILL UNSIGNED NOT NULL,
  `stock_reservado` INT ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`id_producto`, `id_almacen`),
  INDEX `fk_productos_has_almacenes_almacenes1_idx` (`id_almacen` ASC) VISIBLE,
  INDEX `fk_productos_has_almacenes_productos1_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_productos_has_almacenes_productos1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `provisys`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_has_almacenes_almacenes1`
    FOREIGN KEY (`id_almacen`)
    REFERENCES `provisys`.`almacen` (`id_almacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;